assert_spec x86

if {[have_board linux]} {
	puts "The [run_name] scenario requires QEMU networking."
	exit 1
}

create_boot_directory
import_from_depot [depot_user]/src/[base_src] \
                  [depot_user]/pkg/[drivers_nic_pkg] \
                  [depot_user]/src/init \
                  [depot_user]/src/libc \
                  [depot_user]/src/nic_router \
                  [depot_user]/src/openssl \
                  [depot_user]/src/posix \
                  [depot_user]/src/rtc_drv \
                  [depot_user]/src/vfs_jitterentropy \
                  [depot_user]/src/vfs_lxip \
                  [depot_user]/src/vfs
build { app/drill }


install_config {
<config>
	<parent-provides>
		<service name="CPU"/>
		<service name="IO_MEM"/>
		<service name="IO_PORT"/>
		<service name="IRQ"/>
		<service name="LOG"/>
		<service name="PD"/>
		<service name="RM"/>
		<service name="ROM"/>
	</parent-provides>
	<default-route>
		<any-service>  <parent/> <any-child/></any-service>
	</default-route>
	<default caps="100"/>

	<start name="timer">
		<resource name="RAM" quantum="1M"/>
		<provides><service name="Timer"/></provides>
	</start>

	<start name="drivers" caps="1200" managing_system="yes">
		<resource name="RAM" quantum="32M"/>
		<binary name="init"/>
		<route>
			<service name="ROM" label="config"> <parent label="drivers.config"/> </service>
			<service name="Timer"> <child name="timer"/> </service>
			<service name="Uplink"> <child name="nic_router"/> </service>
			<any-service> <parent/> </any-service>
		</route>
	</start>

	<start name="rtc_drv">
		<resource name="RAM" quantum="4M"/>
		<provides> <service name="Rtc"/> </provides>
	</start>

	<start name="nic_router" caps="400">
		<resource name="RAM" quantum="16M"/>
		<provides>
			<service name="Nic"/>
			<service name="Uplink"/>
		</provides>
		<config verbose_domain_state="yes">
			<domain name="uplink">
				<nat domain="downlink"
				     tcp-ports="500"
				     udp-ports="500"
				     icmp-ids="500"/>
			</domain>

			<domain name="downlink" interface="10.0.3.250/24">
				<tcp dst="0.0.0.0/0"> <permit-any domain="uplink"/> </tcp>
				<udp dst="0.0.0.0/0"> <permit-any domain="uplink"/> </udp>
				<dhcp-server ip_first="10.0.3.2"
				             ip_last="10.0.3.2"
				             ip_lease_time_sec="600"
				             dns_config_from="uplink"/>
			</domain>

			<policy label_prefix="drivers -> " domain="uplink"/>
			<policy label_prefix="drill -> " domain="downlink"/>
		</config>
	</start>

	<start name="drill" caps="256">
		<resource name="RAM" quantum="32M"/>
		<config>
			<libc stdout="/dev/log" stderr="/dev/log" rtc="/dev/rtc"
			      rng="/dev/random" socket="/socket"/>
			<vfs>
				<dir name="dev">
					<log/> <rtc/>
					<jitterentropy name="random"/>
					<jitterentropy name="urandom"/>
				</dir>
				<dir name="socket"> <lxip dhcp="yes"/> </dir>
			</vfs>
			<arg value="drill"/>
			<arg value="-T"/>
			<arg value="genode.org"/>
			<arg value="@8.8.8.8"/>
		</config>
	</start>
</config>
}

build_boot_image { drill }

append qemu_args " -nographic -object filter-dump,id=net0,netdev=net0,file=[run_dir]/dump.pcap"

run_genode_until {child "drill" exited with exit value 0.*\n} 120
