#
# Build
#

set build_components {
	test/keynote		
	core init
	
}

build $build_components

create_boot_directory

#
# Generate config
#

set config {
<config verbose="yes">
	<parent-provides>
		<service name="ROM"/>
		<service name="IRQ"/>
		<service name="IO_MEM"/>
		<service name="IO_PORT"/>
		<service name="PD"/>
		<service name="RM"/>
		<service name="CPU"/>
		<service name="LOG"/>
	</parent-provides>
	<default-route>
		<any-service> <parent/> <any-child/> </any-service>
	</default-route>
	<default caps="200"/>
	<start name="test-keynote">
		<resource name="RAM" quantum="32M"/>
	</start>
</config>}

install_config $config

#
# Boot modules
#


build_boot_image [build_artifacts]


run_genode_until {.*exited with exit value 0.*} 20
