#
# \brief  Test of ssh_client
# \author Emery Hemingway
#

assert_spec x86

set build_components {
	app/ssh_client
}

build $build_components

create_boot_directory

import_from_depot \
	[depot_user]/pkg/drivers_managed-pc \
	[depot_user]/pkg/terminal \
	[depot_user]/src/[base_src] \
	[depot_user]/src/init \
	[depot_user]/src/nic_router \
	[depot_user]/src/nitpicker \
	[depot_user]/src/pc_nic_drv \
	[depot_user]/src/vfs \
	[depot_user]/src/vfs_import \
	[depot_user]/src/vfs_lwip \

append config {
<config prio_levels="4">
	<parent-provides>
		<service name="CPU"/>
		<service name="IO_MEM"/>
		<service name="IO_PORT"/>
		<service name="IRQ"/>
		<service name="LOG"/>
		<service name="PD"/>
		<service name="RM"/>
		<service name="ROM"/>
	</parent-provides>
	<default caps="100"/>
	<default-route>
		<any-service> <parent/> </any-service>
	</default-route>

	<start name="timer">
		<resource name="RAM" quantum="1M"/>
		<provides> <service name="Timer"/> </provides>
	</start>

	<start name="drivers_report_rom">
		<binary name="report_rom"/>
		<resource name="RAM" quantum="2M"/>
		<provides>
			<service name="Report"/>
			<service name="ROM"/>
		</provides>
		<config verbose="no">
			<policy label_suffix="capslock" report="null"/>
			<policy label_suffix="numlock" report="null"/>
			<policy label_suffix="system" report="null"/>
			<policy label_suffix="usb_policy" report="null"/>
		</config>
	</start>

	<start name="drivers" caps="5000" managing_system="yes" priority="-1">
		<resource name="RAM" quantum="128M"/>
		<binary name="init"/>
		<provides>
			<service name="Platform"/>
		</provides>
		<route>
			<service name="Capture"> <child name="nitpicker"/> </service>
			<service name="Event"> <child name="nitpicker"/> </service>
			<service name="ROM" label="config"> <parent label="drivers.config"/> </service>
			<service name="ROM" label_last="capslock"> <child name="drivers_report_rom"/> </service>
			<service name="ROM" label_last="numlock"> <child name="drivers_report_rom"/> </service>
			<service name="ROM" label_last="system"> <child name="drivers_report_rom"/> </service>
			<service name="ROM" label_last="usb_policy"> <child name="drivers_report_rom"/> </service>
			<service name="Report"> <child name="drivers_report_rom"/> </service>
			<service name="Timer"> <child name="timer"/> </service>
			<service name="Uplink"> <child name="nic_router"/> </service>
			<any-service> <parent/> </any-service>
		</route>
	</start>

	<start name="nitpicker">
		<resource name="RAM" quantum="4M"/>
		<provides>
			<service name="Gui"/>
			<service name="Capture"/>
			<service name="Event"/>
		</provides>
		<config>
			<capture/> <event/>
			<domain name="default" layer="2" content="client" label="no" focus="click" hover="always"/>
			<default-policy domain="default"/>
		</config>
		<route>
			<service name="Timer"> <child name="timer"/> </service>
			<any-service> <parent/> </any-service>
		</route>
	</start>

	<start name="nic_drv" priority="-1">
		<binary name="pc_nic_drv"/>
		<resource name="RAM" quantum="8M"/>
		<route>
			<service name="Platform"> <child name="drivers" label="nic_drv -> nic"/> </service>
			<service name="Timer"> <child name="timer"/> </service>
			<service name="Uplink"> <child name="nic_router"/> </service>
			<any-service> <parent/> </any-service>
		</route>
	</start>

	<start name="terminal">
		<resource name="RAM" quantum="36M"/>
		<provides> <service name="Terminal"/> </provides>
		<route>
			<service name="ROM" label="config"> <parent label="terminal.config"/> </service>
			<service name="Gui"> <child name="nitpicker" label="terminal"/> </service>
			<service name="Timer"> <child name="timer"/> </service>
			<any-service> <parent/> </any-service>
		</route>
	</start>

	<start name="nic_router" caps="400">
		<resource name="RAM" quantum="36M"/>
		<provides>
			<service name="Nic"/>
			<service name="Uplink"/>
		</provides>
		<config verbose_domain_state="yes">

			<domain name="uplink">
				<nat domain="downlink"
				     tcp-ports="16384"
				     udp-ports="16384"
				     icmp-ids="16384"/>
			</domain>

			<domain name="downlink" interface="10.10.10.250/24">
				<dhcp-server ip_first="10.10.10.2" ip_last="10.10.10.25">
					<dns-server ip="8.8.8.8"/>
					<dns-server ip="1.1.1.1"/>
				</dhcp-server>
				<tcp  dst="0.0.0.0/0"> <permit-any domain="uplink"/> </tcp>
				<udp  dst="0.0.0.0/0"> <permit-any domain="uplink"/> </udp>
				<icmp dst="0.0.0.0/0" domain="uplink"/>
			</domain>

			<policy label_prefix="ssh_client" domain="downlink"/>
			<policy label_prefix="nic_drv"    domain="uplink"/>
		</config>
		<route>
			<service name="Timer"> <child name="timer"/> </service>
			<any-service> <parent/> </any-service>
		</route>
	</start>

	<start name="ssh_client" caps="500">
		<resource name="RAM" quantum="32M"/>
		<config>
			<vfs>
				<ram/>
				<dir name="dev">
					<log/> <null/>
					<inline name="rtc">2000-01-01 00:00</inline>
					<inline name="random">g0Kof/YMRG8NLASiukpI6f5QQinTPyOpzkreUXr3HCMiRVpn14GkiyQ0ezrN2KAK</inline>
				</dir>
				<dir name="socket"> <lwip dhcp="yes"/> </dir>
				<import>
					<!-- cange this to match you ssh destinations -->
					<inline name="host">
						<host name="10.10.10.10" user="user" pass="ssap" known="no"/>
					</inline>
				</import>
			</vfs>
			<libc stdout="/dev/log" stderr="/dev/log" rtc="/dev/rtc" rng="/dev/random" socket="/socket"/>
		</config>
		<route>
			<service name="Nic"> <child name="nic_router"/> </service>
			<service name="Terminal"> <child name="terminal"/> </service>
			<service name="Timer"> <child name="timer"/> </service>
			<any-service> <parent/> </any-service>
		</route>
	</start>

</config> }

install_config $config

build_boot_image [build_artifacts]

append qemu_args " -object filter-dump,id=net0,netdev=net0,file=[run_dir].pcap"
append qemu_args " -usbdevice mouse -usbdevice keyboard "

run_genode_until forever
